Website_QLy_BanHang/Website_QLy_BanHang/Areas/Admin/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices.ComTypes;
using System.Web;
using System.Web.Mvc;
using MyClass.DAO;
using MyClass.Model;
using Website_QLy_BanHang.Library;

namespace Website_QLy_BanHang.Areas.Admin.Controllers
{
    public class SupplierController : Controller
    {
        SuppliersDAO suppliersDAO = new SuppliersDAO();

        //////////////////////////////////////////////////////////////     
        // GET: Admin/Supplier/Index
        public ActionResult Index()
        {
            // hien thi cac mau tin o trang index ( status = 1,2 hay DAO = Index)
            return View(suppliersDAO.getList("Index"));
        }

        //////////////////////////////////////////////////////////////
        // GET: Admin/Supplier/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Không tồn tại nhà cung cấp");
            }
            Suppliers suppliers = suppliersDAO.getRow(id);
            if (suppliers == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Không tồn tại nhà cung cấp");
                return RedirectToAction("Index");
            }
            return View(suppliers);
        }

        //////////////////////////////////////////////////////////////
        // GET: Admin/Supplier/Create
        public ActionResult Create()
        {
            ViewBag.ListOrder = new SelectList(suppliersDAO.getList("Index"), "Order", "Name");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Suppliers suppliers)
        {
            if (ModelState.IsValid)
            {   //xu ly tu dong cho cac truong: CreateAt/By, UpdateAt/By, Slug, OrderBy
                //Xu Ly tu dong CreateAt
                suppliers.CreateAt = DateTime.Now;
                //Xu Ly tu dong Update
                suppliers.UpdateAt = DateTime.Now;             
                //Xu Ly tu dong Order
                if (suppliers.Order == null)
                {
                    suppliers.Order = 1;
                }
                else
                {
                    suppliers.Order += 1;
                }
                //Xu Ly tu dong Slug
                suppliers.Slug = XString.Str_Slug(suppliers.Name);

                //xu ly cho phan upload hình ảnh
                var img = Request.Files["img"];//lay thong tin file
                if (img.ContentLength != 0)
                {
                    string[] FileExtentions = new string[] { ".jpg", ".jpeg", ".png", ".gif" };
                    //kiem tra tap tin co hay khong
                    if (FileExtentions.Contains(img.FileName.Substring(img.FileName.LastIndexOf("."))))//lay phan mo rong cua tap tin
                    {
                        string slug = suppliers.Slug;
                        //ten file = Slug + phan mo rong cua tap tin
                        string imgName = slug + img.FileName.Substring(img.FileName.LastIndexOf("."));
                        suppliers.Image = imgName;
                        //upload hinh
                        string PathDir = "~/Public/img/supplier/";
                        string PathFile = Path.Combine(Server.MapPath(PathDir), imgName);
                        img.SaveAs(PathFile);
                    }
                }//ket thuc phan upload hinh anh

                //Them mau tin vao db
                suppliersDAO.Insert(suppliers);
                //Thong bao thanh cong
                TempData["message"] = new XMessage("success", "Thêm nhà cung cấp thành công");
                return RedirectToAction("Index");
            }
            ViewBag.ListOrder = new SelectList(suppliersDAO.getList("Index"), "Order", "Name");
            return View(suppliers);
        }

        //////////////////////////////////////////////////////////////
        // GET: Admin/Supplier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Không tồn tại nhà cung cấp");
            }
            Suppliers suppliers = suppliersDAO.getRow(id);// tim kiem 1 mau tin co Id = Id
            if (suppliers == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Không tồn tại nhà cung cấp");
            }
            ViewBag.ListOrder = new SelectList(suppliersDAO.getList("Index"), "Order", "Name");
            return View(suppliers);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Suppliers suppliers)
        {
            if (ModelState.IsValid)
            {
                //xu ly tu dong cho cac truong: CreateAt/By, UpdateAt/By, Slug, OrderBy
                //Xu Ly tu dong Update
                suppliers.UpdateAt = DateTime.Now;

                //Xu Ly tu dong Order
                if (suppliers.Order == null)
                {
                    suppliers.Order = 1;
                }
                else
                {
                    suppliers.Order += 1;
                }
                //Xu Ly tu dong Slug
                suppliers.Slug = XString.Str_Slug(suppliers.Name);

                var img = Request.Files["img"];//lay thong tin file
                string PathDir = "~/Public/img/supplier/";
                if (img.ContentLength != 0 && suppliers.Image != null) // ton tai mot logo cua Nha cung cap
                {
                    //xoa anh cu
                    string DelPath = Path.Combine(Server.MapPath(PathDir), suppliers.Image);
                    System.IO.File.Delete(DelPath);
                }
                //Upload logo moi cua nha cung ca
                //Truoc khi cap nhap lai anh moi thi xoa anh cu
               

                //xu ly cho phan upload hình ảnh
                
                if (img.ContentLength != 0)
                {
                    string[] FileExtentions = new string[] { ".jpg", ".jpeg", ".png", ".gif" };
                    //kiem tra tap tin co hay khong
                    if (FileExtentions.Contains(img.FileName.Substring(img.FileName.LastIndexOf("."))))//lay phan mo rong cua tap tin
                    {
                        string slug = suppliers.Slug;
                        //ten file = Slug + phan mo rong cua tap tin
                        string imgName = slug + img.FileName.Substring(img.FileName.LastIndexOf("."));
                        suppliers.Image = imgName;
                        //upload hinh
                       
                        string PathFile = Path.Combine(Server.MapPath(PathDir), imgName);
                        img.SaveAs(PathFile);
                    }
                }//ket thuc phan upload hinh anh

                //Cap nhap mau tin
                suppliersDAO.Update(suppliers);
                //Thong bao thanh cong
                TempData["message"] = new XMessage("success", "Cập nhập nhà cung cấp thành công");
                return RedirectToAction("Index");
            }
            return View(suppliers);
        }

        //////////////////////////////////////////////////////////////
        // GET: Admin/Supplier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Không tồn tại nhà cung cấp");
            }
            Suppliers suppliers = suppliersDAO.getRow(id);
            if (suppliers == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Không tồn tại nhà cung cấp");
            }
            return View(suppliers);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Suppliers suppliers =suppliersDAO.getRow(id); // tim kiem 1 mau tin co Id = Id

            var img = Request.Files["img"];//lay thong tin file
            string PathDir = "~/Public/img/supplier/";
            //Xoa au tin ra khoi db
            if (suppliersDAO.Delete(suppliers) == 1)
            {
                //Xu ly cho muc xoa hinh anh
                if (suppliers.Image != null)
                {
                    string DelPath = Path.Combine(Server.MapPath(PathDir), suppliers.Image);
                    System.IO.File.Delete(DelPath);
                }
            }
            //Thong bao xoa thanh cong
            TempData["message"] = new XMessage("success", "Xóa nhà cung cấp thành công");
            return RedirectToAction("Index");
        }

        // GET: Admin/Supplier/Status/5
        public ActionResult Status(int? id)
        {
            if (id == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Cập nhập trạng thái thất bại");
                return RedirectToAction("Index");
            }
            // Truy van id
            Suppliers suppliers = suppliersDAO.getRow(id);
            if (suppliers == null)
            {
                //Thong bao that bai
                TempData["message"] = new XMessage("danger", "Cập nhập trạng thái thất bại");
                return RedirectToAction("Index");
            }
            else
            {
                // Chuyen Doi Trang Thai cua Status tu 1 <-> 2
                suppliers.Status = (suppliers.Status == 1) ? 2 : 1;

                //Cap nhap gia tri UpdateAt
                suppliers.UpdateAt = DateTime.Now;

                //Cap nhap lai DB

Website_QLy_BanHang/Website_QLy_BanHang/Areas/Admin/Views/Supplier/Create.cshtml
@model MyClass.Model.Suppliers

@{
    ViewBag.Title = "Tạo mới nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Create", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="wrapper">
        <!-- Main Sidebar Container -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <strong class="text-danger">TẠO MỚI NHÀ CUNG CẤP</strong>
                            </div>
                            <div class="col-md-6 text-right">
                                <a href="@Url.Action("Index","Supplier")" class="btn-sm btn-info"><i class="fa fa-long-arrow-alt-left"></i> Quay lại</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="row">
                            @*Phần điền thông tin*@
                            <div class="col-md-9">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MetaDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.MetaDesc, new { @class = "form-control", @row = "5" })
                                        @Html.ValidationMessageFor(model => model.MetaDesc, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MetaKey, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.MetaKey, new { @class = "form-control", @row = "5" })
                                        @Html.ValidationMessageFor(model => model.MetaKey, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            @*Phần chọn từ danh sách*@
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Logo nhà cung cấp<span class="text-danger"></span></label>
                                    <div class="col-md-10">
                                        <input name="img" type="file" class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.Order, (SelectList)@ViewBag.ListOrder, "Sắp xếp", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.Status, new[] { new SelectListItem { Text = "Không xuất bản", Value = "2" }, new SelectListItem { Text = "Xuất bản", Value = "1" } }, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <button class="btn-sm btn-success" type="submit" name="create">Lưu[Thêm]<i class="fa fa-save"></i></button>
                        </div><!--Card- row-->
                    </div> <!-- /.card-body-->
                </div><!-- /.card -->
            </section><!-- /.content -->
        </div> <!-- /.content-wrapper -->
    </div><!-- ./wrapper -->








}

Website_QLy_BanHang/Website_QLy_BanHang/Areas/Admin/Views/Supplier/Delete.cshtml
@model MyClass.Model.Suppliers
@{
    ViewBag.Title = "Xác nhận xóa dữ liệu";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="wrapper">
        <!-- Main Sidebar Container -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <strong class="text-danger">XÁC NHẬN XÓA DỮ LIỆU</strong>
                            </div>

                            <div class="col-md-6 text-right">
                                <a href="@Url.Action("Index","Supplier")" class="btn-sm btn-info"><i class="fa fa-long-arrow-alt-left"></i> Quay lại</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        @Html.Partial("Message")
                        <table class="table table-bordered table-striped" id="myTable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                                    <th>@Html.DisplayNameFor(model => model.Image)</th>
                                    <th>@Html.DisplayNameFor(model => model.Slug)</th>
                                    <th>@Html.DisplayNameFor(model => model.Order)</th>
                                    <th>@Html.DisplayNameFor(model => model.Phone)</th>
                                    <th>@Html.DisplayNameFor(model => model.Email)</th>
                                    <th>Xác nhận</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><input type="checkbox" name="id" value="" /></td>
                                    <td>@Html.DisplayFor(model => model.Id)</td>
                                    <td>@Html.DisplayFor(model => model.Name)</td>
                                    <td><img src="~/Public/img/supplier/@Model.Image" alt="Img" class="img-fluid" /></td>
                                    <td>@Html.DisplayFor(model => model.Slug)</td>
                                    <td>@Html.DisplayFor(model => model.Order)</td>
                                    <td>@Html.DisplayFor(model => model.Phone)</td>
                                    <td>@Html.DisplayFor(model => model.Email)</td>
                                    <td>
                                        <div class="form-actions no-color">
                                            <button class="btn-sm btn-danger" input type="submit" name="Delete"> Xóa [Del] <i class="fa fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div> <!-- /.card-footer-->
                </div><!-- /.card -->
            </section><!-- /.content -->
        </div> <!-- /.content-wrapper -->
    </div><!-- ./wrapper -->
}

Website_QLy_BanHang/Website_QLy_BanHang/Areas/Admin/Views/Supplier/Details.cshtml
@model MyClass.Model.Suppliers
@{
    ViewBag.Title = "Chi tiết nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="wrapper">
        <!-- Main Sidebar Container -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <strong class="text-danger">CHI TIẾT NHÀ CUNG CẤP</strong>
                            </div>

                            <div class="col-md-6 text-right">
                                <a href="@Url.Action("Index","Supplier")" class="btn-sm btn-info"><i class="fa fa-long-arrow-alt-left"></i> Quay lại</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        @Html.Partial("Message")
                        <table class="table table-bordered table-striped" id="myTable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                                    <th>@Html.DisplayNameFor(model => model.Image)</th>
                                    <th>@Html.DisplayNameFor(model => model.Slug)</th>
                                    <th>@Html.DisplayNameFor(model => model.Order)</th>
                                    <th>@Html.DisplayNameFor(model => model.Phone)</th>
                                    <th>@Html.DisplayNameFor(model => model.Email)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><input type="checkbox" name="id" value="" /></td>
                                    <td>@Html.DisplayFor(model => model.Id)</td>
                                    <td>@Html.DisplayFor(model => model.Name)</td>
                                    <td><img src="~/Public/img/supplier/@Model.Image" alt="Img" class="img-fluid" /></td>
                                    <td>@Html.DisplayFor(model => model.Slug)</td>
                                    <td>@Html.DisplayFor(model => model.Order)</td>
                                    <td>@Html.DisplayFor(model => model.Phone)</td>
                                    <td>@Html.DisplayFor(model => model.Email)</td>
                                </tr>
                            </tbody>
                        </table>

                    </div> <!-- /.card-footer-->
                </div><!-- /.card -->
            </section><!-- /.content -->
        </div> <!-- /.content-wrapper -->
    </div><!-- ./wrapper -->
}

Website_QLy_BanHang/Website_QLy_BanHang/Areas/Admin/Views/Supplier/Index.cshtml
@model IEnumerable<MyClass.Model.Suppliers>
@*
    Nếu bạn chỉ cần hiển thị 1 mẫu tin thì không cần IEnumerable
    IndexedString thì có nhiều hơn 1 mẫu tin -> phải có IEnumerable
*@


@{
    ViewBag.Title = "Trang chủ nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@section header{
    <link rel="stylesheet" href="~/Public/css/dataTables.dataTables.min.css" />
}
@section footer{
    <script src="~/Public/js/dataTables.min.js"></script>
    <script>let table = new DataTable('#myTable');</script>
}

<div class="wrapper">
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger">DANH MỤC NHÀ CUNG CẤP</strong>
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="@Url.Action("Create","Supplier")" class="btn-sm btn-success"><i class="fa fa-plus"></i> Thêm</a>
                            <a href="@Url.Action("Trash","Supplier")" class="btn-sm btn-danger"><i class="fa fa-trash"></i> Thùng rác</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @Html.Partial("Message")
                    <table class="table table-striped" id="myTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>ID</th>
                                <th>@Html.DisplayNameFor(model => model.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Image)</th>
                                <th>@Html.DisplayNameFor(model => model.Slug)</th>
                                <th>@Html.DisplayNameFor(model => model.Order)</th>
                                <th>@Html.DisplayNameFor(model => model.Phone)</th>
                                <th>@Html.DisplayNameFor(model => model.Email)</th>
                                <th>Chức năng</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><input type="checkbox" name="checkid" value=""/></td>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td><img src="~/Public/img/supplier/@item.Image" alt="Image" class="img-fluid" /></td>
                                    <td>@Html.DisplayFor(modelItem => item.Slug)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Order)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                    <td>
                                        @if (item.Status == 1)
                                        {
                                            <a href="@Url.Action("Status", "Supplier", new { id = item.Id })" class="btn-sm btn-success"><i class="fa fa-toggle-on"></i></a>

                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Status", "Supplier", new { id = item.Id })" class="btn-sm btn-danger"><i class="fa fa-toggle-off"></i></a>
                                        }
                                        <a href="@Url.Action("Edit","Supplier", new { id = item.Id })" class="btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                                        <a href="@Url.Action("Details","Supplier", new { id = item.Id })" class="btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                        <a href="@Url.Action("DelTrash","Supplier", new { id = item.Id })" class="btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div> <!-- /.card-footer-->
            </div><!-- /.card -->
        </section><!-- /.content -->
    </div> <!-- /.content-wrapper -->
</div><!-- ./wrapper -->