Website_QLy_BanHang/Website_QLy_BanHang/Controllers/ModuleController.cs
using MyClass.DAO;
using MyClass.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Website_QLy_BanHang.Controllers
{
    public class ModuleController : Controller
    {
        ///////////////////////////////////////////////////////////////////////////
        MenusDAO menusDAO = new MenusDAO();

        ///////////////////////////////////////////////////////////////////////////
        // GET: Mainmenu
        public ActionResult MainMenu()
        {
            List<Menus> list = menusDAO.getListByParentId(0, "MainMenu");
            return View("MainMenu", list);
        }
        ///////////////////////////////////////////////////////////////////////////
        // GET: MainmenuSub
        public ActionResult MainMenuSub(int id)
        {
            List<Menus> list = menusDAO.getListByParentId(id, "MainMenu");
            //tra ve dong hien hanh cua menu co id = id
            Menus menus = menusDAO.getRow(id);
            if (list.Count == 0)//menu khong co cap con
            {
                return View("MainMenuSub_0", menus);
            }
            else//menu co cap con
            {
                ViewBag.Menu2cap = menus;
                return View("MainMenuSub_1", list);
            }
        }

        ///////////////////////////////////////////////////////////////////////////
        public ActionResult Slider()
        {
            SlidersDAO slidersDAO = new SlidersDAO();
            List<Sliders> list = slidersDAO.getListByPosition("slider");//ten ham dat tuy y
            return View("Slider", list);
        }

        ///////////////////////////////////////////////////////////////////////////
        public ActionResult CategoriesList()
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            List<Categories> list = categoriesDAO.getListByPareantId(0);
            return View("CategoriesList", list);
        }

        ///////////////////////////////////////////////////////////////////////////
        ///Footer Menu
        public ActionResult MenuFooter()
        {
            MenusDAO menusDAO = new MenusDAO();
            List<Menus> list = menusDAO.getListByParentId(0, "Footer");
            return View("MenuFooter", list);
        }
    }
}

Website_QLy_BanHang/Website_QLy_BanHang/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyClass.DAO;
using MyClass.Model;

namespace Website_QLy_BanHang.Controllers
{
    public class SiteController : Controller
    {
        LinksDAO linksDAO = new LinksDAO();
        /////////////////////////////////////////////////////////////////////////////
        // GET: Site
        public ActionResult Index(string slug = null)
        {
            if (slug == null)
            {
                //chuyen ve trang chu
                return this.Home();
            }
            else
            {
                //tim slug co trong bang link
                Links links = linksDAO.getRow(slug);
                //kiem tra slug co ton tai trong bang Links hay khong
                if (links != null)
                {
                    //lay ra Type trong bang link
                    string typelink = links.Type;
                    switch (typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug);
                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }
                        default:
                            {
                                return this.Error404(slug);
                            }
                    }
                }
                else
                {
                    //slug khong co trong bang Links
                    //slug co trong bang product?
                    //slug co trong bang Post voi PostType==post?
                    ProductsDAO productsDAO = new ProductsDAO();
                    PostsDAO postsDAO = new PostsDAO();

                    //tim slug co trong bang Products
                    Products products = productsDAO.getRow(slug);
                    if (products != null)
                    {
                        return this.ProductDetail(slug);
                    }
                    else
                    {
                        Posts posts = postsDAO.getRow(slug);
                        if (posts != null)
                        {
                            return this.PostDetail(posts);
                        }
                        else
                        {
                            return this.Error404(slug);
                        }
                    }
                }
            }
        }

        /////////////////////////////////////////////////////////////////////////////
        //Trang chu
        public ActionResult Home()
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            List<Categories> list = categoriesDAO.getListByPareantId(0);
            return View("Home", list);
        }

        /////////////////////////////////////////////////////////////////////////////
        //Site/Product
        public ActionResult Product()
        {
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.getListBylimit(10);
            return View("Product", list);
        }

        /////////////////////////////////////////////////////////////////////////////
        //Site/Post
        public ActionResult Post()
        {
            return View("Post");
        }

        /////////////////////////////////////////////////////////////////////////////
        //Site/ProductCategory
        public ActionResult ProductCategory(string slug)
        {
            //Lay categories dua vao Slug
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            Categories categories = categoriesDAO.getRow(slug);

            //hien thi noi dung cua mau tin
            ViewBag.Categories = categories;
            //hien thi toan bo cac shan pham ung voi tung loai
            //hien thi theo 3 cap: cha - con - con cua con
            List<int> listcatid = new List<int>();
            //cap 1
            listcatid.Add(categories.Id);

            //cap 2
            List<Categories> listcategories2 = categoriesDAO.getListByPareantId(categories.Id);
            if (listcategories2.Count() != 0)
            {
                foreach (var categories2 in listcategories2)
                {
                    listcatid.Add(categories2.Id);
                    //cap 3
                    List<Categories> listcategories3 = categoriesDAO.getListByPareantId(categories2.Id);
                    if (listcategories3.Count() != 0)
                    {
                        foreach (var categories3 in listcategories3)
                        {
                            listcatid.Add(categories3.Id);
                        }
                    }
                }
            }

            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.getListByListCatId(listcatid, 10);
            return View("ProductCategory", list);
        }

        /////////////////////////////////////////////////////////////////////////////
        //Site/PostTopic
        public ActionResult PostTopic(string slug)
        {
            return View("PostTopic");
        }

        /////////////////////////////////////////////////////////////////////////////
        //Site/PostPage
        public ActionResult PostPage(string slug)
        {
            PostsDAO postsDAO = new PostsDAO();
            Posts posts = postsDAO.getRow(slug);
            return View("PostPage", posts);
        }

        /////////////////////////////////////////////////////////////////////////////
        //Site/Error404
        public ActionResult Error404(string slug)
        {
            return View("Error404");
        }

        /////////////////////////////////////////////////////////////////////////////
        //Product/Details
        public ActionResult ProductDetail(string slug)
        {
            // Hien thi noi dung cua san pham
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.GetProductDetailBySlug(slug);

            // Lay CatID cua san pham hien tai
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            int catid = list.First().CatID;

            // Lay danh sach san pham cung loai (related products)
            List<ProductInfo> relatedProducts = productsDAO.GetProductDetailByCategoryId(catid);

            // Truyen danh sach san pham cung loai cho View
            ViewBag.RelatedProducts = relatedProducts;

            //tra ve danh sach cho tiet san pham cho list
            return View("ProductDetail", list);
        }

        /////////////////////////////////////////////////////////////////////////////
        //Post/Details
        public ActionResult PostDetail(Posts posts)
        {

            return View("PostDetail");
        }

        /////////////////////////////////////////////////////////////////////////////
        //HomeProduct
        public ActionResult HomeProduct(int id)
        {
            CategoriesDAO categoriesDAO = new CategoriesDAO();
            Categories categories = categoriesDAO.getRow(id);
            ViewBag.Categories = categories;
            //hien thi toan bo cac shan pham ung voi tung loai
            //hien thi theo 3 cap: cha - con - con cua con
            List<int> listcatid = new List<int>();
            //cap 1
            listcatid.Add(id);

            //cap 2
            List<Categories> listcategories2 = categoriesDAO.getListByPareantId(id);
            if (listcategories2.Count() != 0)
            {
                foreach (var categories2 in listcategories2)
                {
                    listcatid.Add(categories2.Id);
                    //cap 3
                    List<Categories> listcategories3 = categoriesDAO.getListByPareantId(categories2.Id);
                    if (listcategories3.Count() != 0)
                    {
                        foreach (var categories3 in listcategories3)
                        {
                            listcatid.Add(categories3.Id);
                        }
                    }
                }
            }
            ProductsDAO productsDAO = new ProductsDAO();
            List<ProductInfo> list = productsDAO.getListByListCatId(listcatid, 10);
            return View("HomeProduct", list);
        }
    }
}

Website_QLy_BanHang/Website_QLy_BanHang/Views/Site/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<body>
    <main class="site-main">
        @*================ Hero banner start =================*@
        <section class="hero-banner">
            <div class="container">
                <div class="row no-gutters align-items-center pt-60px">
                    <div class="col-5 d-none d-sm-block">
                        <div class="hero-banner__img">
                            <img class="img-fluid" src="Public/img/home/hero-banner.png" alt="">
                        </div>
                    </div>
                    <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
                        <div class="hero-banner__content">
                            <h4>Shop is fun</h4>
                            <h1>Browse Our Premium Product</h1>
                            <p>Us which over of signs divide dominion deep fill bring they're meat beho upon own earth without morning over third. Their male dry. They are great appear whose land fly grass.</p>
                            <a class="button button-hero" href="#">Browse Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @*================ Hero banner start =================*@

        @*================ Hero Carousel start =================*@
        @Html.Action("Slider", "Module")
        @*================ Hero Carousel end =================*@

        @*================ trending product section start =================*@
        @Html.Action("Product", "Site")
        @*================ trending product section end =================*@
        <section class="section-margin calc-60px">
            <div class="container">
                @foreach (var item in Model)
                {
                    @Html.Action("HomeProduct", "Site", new { @id = item.Id })
                }
            </div>
        </section>

        @*================ offer section start =================*@
        <section class="offer" id="parallax-1" data-anchor-target="#parallax-1" data-300-top="background-position: 20px 30px" data-top-bottom="background-position: 0 20px">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5">
                        <div class="offer__content text-center">
                            <h3>Up To 50% Off</h3>
                            <h4>Winter Sale</h4>
                            <p>Him she'd let them sixth saw light</p>
                            <a class="button button--active mt-3 mt-xl-4" href="#">Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @*================ offer section end =================*@

        @*================ Best Selling item  carousel =================*@

        @*================ Best Selling item  carousel end =================*@

        @*================ Blog section start =================*@
        <section class="blog">
            <div class="container">
                <div class="section-intro pb-60px">
                    <p>Popular Item in the market</p>
                    <h2>Latest <span class="section-intro__style">News</span></h2>
                </div>

                <div class="row">
                    <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                        <div class="card card-blog">
                            <div class="card-blog__img">
                                <img class="card-img rounded-0" src="Public/img/blog/blog1.png" alt="">
                            </div>
                            <div class="card-body">
                                <ul class="card-blog__info">
                                    <li><a href="#">By Admin</a></li>
                                    <li><a href="#"><i class="ti-comments-smiley"></i> 2 Comments</a></li>
                                </ul>
                                <h4 class="card-blog__title"><a href="single-blog.html">The Richland Center Shooping News and weekly shooper</a></h4>
                                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>
                                <a class="card-blog__link" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                        <div class="card card-blog">
                            <div class="card-blog__img">
                                <img class="card-img rounded-0" src="Public/img/blog/blog2.png" alt="">
                            </div>
                            <div class="card-body">
                                <ul class="card-blog__info">
                                    <li><a href="#">By Admin</a></li>
                                    <li><a href="#"><i class="ti-comments-smiley"></i> 2 Comments</a></li>
                                </ul>
                                <h4 class="card-blog__title"><a href="single-blog.html">The Shopping News also offers top-quality printing services</a></h4>
                                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>
                                <a class="card-blog__link" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                        <div class="card card-blog">
                            <div class="card-blog__img">
                                <img class="card-img rounded-0" src="Public/img/blog/blog3.png" alt="">
                            </div>
                            <div class="card-body">
                                <ul class="card-blog__info">
                                    <li><a href="#">By Admin</a></li>
                                    <li><a href="#"><i class="ti-comments-smiley"></i> 2 Comments</a></li>
                                </ul>
                                <h4 class="card-blog__title"><a href="single-blog.html">Professional design staff and efficient equipment you’ll find we offer</a></h4>
                                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>
                                <a class="card-blog__link" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @*================ Blog section end =================*@

        @*================ Subscribe section start =================*@
        <section class="subscribe-position">
            <div class="container">
                <div class="subscribe text-center">
                    <h3 class="subscribe__title">Get Update From Anywhere</h3>
                    <p>Bearing Void gathering light light his eavening unto dont afraid</p>
                    <div id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe-form form-inline mt-5 pt-1">
                            <div class="form-group ml-sm-auto">
                                <input class="form-control mb-1" type="email" name="EMAIL" placeholder="Enter your email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '">
                                <div class="info"></div>
                            </div>
                            <button class="button button-subscribe mr-auto mb-1" type="submit">Subscribe Now</button>
                            <div style="position: absolute; left: -5000px;">
                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </section>
        @*================ Subscribe section end =================*@
    </main>
</body>

Website_QLy_BanHang/Website_QLy_BanHang/Views/Site/HomeProduct.cshtml
@model IEnumerable<MyClass.Model.ProductInfo>

@{
    var item = ViewBag.Categories;
}

@if (Model.Count() != 0)
{

    <div class="section-intro pb-60px">
        <p><a href="~/@item.Slug">Danh mục sản phẩm theo loại</a></p>
        <h2>
            <span class="section-intro__style">@item.Name</span>
        </h2>
    </div>
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div class="card text-center card-product">
                    <div class="card-product__img">
                        <img class="card-img" src="Public/img/product/@product.Image" alt="">
                        <ul class="card-product__imgOverlay">
                            <li><button><i class="ti-search"></i></button></li>
                            <li>
                                <a href="@Url.Action("AddCart","Giohang", new {productid = product.Id})">
                                    <span class="custom-button">
                                        <i class="ti-shopping-cart"></i>
                                    </span>
                                </a>
                            </li>
                            <li><button><i class="ti-heart"></i></button></li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <h4 class="card-product__title"><a href="@product.Slug">@product.Name</a></h4>
                        <p strong class="card-product__price text-success">@string.Format("{0:0,0.00,00}", @product.Price)<sup>đ</sup></p>
                        <del><span class="danger card-product__price text-danger">@string.Format("{0:0,0.00,00}", @product.SalePrice)</span></del><sup>đ</sup>
                    </div>
                </div>
            </div>
        }
    </div>
}

Website_QLy_BanHang/Website_QLy_BanHang/Views/Site/PostPage.cshtml
@model MyClass.Model.Posts

@{
    ViewBag.Title = "PostPage";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<body>
    <!-- ================ start banner area ================= -->
    <section class="blog-banner-area" id="blog">
        <div class="container h-100">
            <div class="blog-banner">
                <div class="text-center">
                    <h1>@Model.Title</h1>
                    <nav aria-label="breadcrumb" class="banner-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Chi tiết bài viết</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ end banner area ================= -->
    <!--================Blog Area =================-->
    <section class="blog_area single-post-area py-80px section-margin--small">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="~/Public/img/page/@Model.Image" alt="">
                            </div>
                        </div>
                        
                        <div class="col-lg-9 col-md-9 blog_details">
                            @Model.Detail
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Chủ đề bài viết</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="#" class="d-flex justify-content-between">
                                        <p>Technology</p>
                                        <p>37</p>
                                    </a>
                                </li>
                            </ul>
                            <div class="br"></div>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
</body>

Website_QLy_BanHang/Website_QLy_BanHang/Views/Site/PostTopic.cshtml
@{
    ViewBag.Title = "PostTopic";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>PostTopic</h2>

Website_QLy_BanHang/Website_QLy_BanHang/Views/Site/Product.cshtml
@model IEnumerable<MyClass.Model.ProductInfo>

@{
    var item = ViewBag.Categories;
}

<section class="section-margin calc-60px">
    <div class="container">
        <div class="section-intro pb-60px">
            <p>Tất cả sản phẩm</p>
            <h2>Tất cả <span class="section-intro__style">sản phẩm</span></h2>
        </div>
        <div class="row">
            @foreach (var product in Model)
            {
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div class="card text-center card-product">
                        <div class="card-product__img">
                            <img class="card-img" src="~/Public/img/product/@product.Image" alt="">
                            <ul class="card-product__imgOverlay">
                                <li><button><i class="ti-search"></i></button></li>
                                <li>
                                    <a href="@Url.Action("AddCart","Giohang", new { productid = product.Id})">
                                        <span class="custom-button">
                                            <i class="ti-shopping-cart"></i>
                                        </span>
                                    </a>
                                </li>
                                <li><button><i class="ti-heart"></i></button></li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <p>@product.CatName</p>
                            <h4 class="card-product__title"><a href="@product.Slug">@product.Name</a></h4>
                            <p strong class="card-product__price text-success">@string.Format("{0:0,0.00,00}", @product.Price)<sup>đ</sup></p>
                            <del><span class="danger card-product__price text-danger">@string.Format("{0:0,0.00,00}", @product.SalePrice)</span></del><sup>đ</sup>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

Website_QLy_BanHang/Website_QLy_BanHang/Views/Site/ProductCategory.cshtml
@model IEnumerable<MyClass.Model.ProductInfo>

@{
    ViewBag.Title = "ProductCategory";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

@{
    var item = ViewBag.Categories;
}

<body>
    <!-- ================ start banner area ================= -->
    <section class="blog-banner-area" id="category">
        <div class="container h-100">
            <div class="blog-banner">
                <div class="text-center">
                    <h1 class="text-uppercase">@item.Name</h1>
                    <nav aria-label="breadcrumb" class="banner-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@item.Slug">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">@item.Name</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ end banner area ================= -->
    <!-- ================ category section start ================= -->
    <section class="section-margin--small mb-5">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-4 col-md-5">
                    @* Category List Begin *@
                    @Html.Action("CategoriesList", "Module")
                </div>
                @* Category List End *@

                <div class="col-xl-9 col-lg-8 col-md-7">
                    <!-- Start Best Seller -->
                    <section class="lattest-product-area pb-40 category-list">
                        <div class="row">
                            @foreach (var productItem in Model)
                            {
                                <div class="col-md-6 col-lg-4">
                                    <div class="card text-center card-product">
                                        <div class="card-product__img">
                                            <img class="card-img" src="Public/img/product/@productItem.Image" alt="">
                                            <ul class="card-product__imgOverlay">
                                                <li><button><i class="ti-search"></i></button></li>
                                                <li>
                                                    <a href="@Url.Action("AddCart","Giohang", new {productid = @productItem.Id})">
                                                        <span class="custom-button">
                                                            <i class="ti-shopping-cart"></i>
                                                        </span>
                                                    </a>
                                                </li>
                                                <li><button><i class="ti-heart"></i></button></li>
                                            </ul>
                                        </div>
                                        <div class="card-body">
                                            <p>@productItem.CatName</p>
                                            <h4 class="card-product__title"><a href="@productItem.Slug">@productItem.Name</a></h4>
                                            <p strong class="card-product__price text-success">@string.Format("{0:0,0.00,00}", @productItem.Price)<sup>đ</sup></p>
                                            <del><span class="danger card-product__price text-danger">@string.Format("{0:0,0.00,00}", @productItem.SalePrice)</span></del><sup>đ</sup>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </section><!-- End Best Seller -->
                </div>
            </div>
        </div>
    </section>
    <!-- ================ category section end ================= -->
</body>